# Generated by Django 4.1.1 on 2023-12-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='completion_level',
            field=models.IntegerField(default=0),
        ),
    ]
