# Generated by Django 4.2.7 on 2023-12-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='input_data',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
